language: java
branches:
  only:
  - master
  - jomc-cli-1.x
jdk:
  - openjdk7
os:
  - linux
  - os x
script: "mvn --show-version --errors --batch-mode clean verify"
cache:
    directories:
    - $HOME/.m2
notifications:
    email:
    - cs@schulte.it
